# Neighborhood Computations

In [1]:
import numpy as np
import igl
import meshplot

In [2]:
bunny_v, bunny_f = igl.read_triangle_mesh("data/bunny.off")
cube_v, cube_f = igl.read_triangle_mesh("data/cube.obj")
sphere_v, sphere_f = igl.read_triangle_mesh("data/sphere.obj")

In [3]:
meshplot.plot(bunny_v, bunny_f, shading={"wireframe": True})

D:\Anaconda\envs\GM\lib\site-packages\jupyter_client\session.py:716: UserWarning: Message serialization failed with:
Out of range float values are not JSON compliant
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
  content = self.pack(content)


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-0.016860…

In [4]:
meshplot.plot(cube_v, cube_f, shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

In [5]:
meshplot.plot(sphere_v, sphere_f, shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

## Vertex-to-Face Relations

In [6]:
print(igl.vertex_triangle_adjacency(cube_f, len(cube_f)))

(array([ 0,  6,  7, 10, 11,  0,  1,  7,  8,  0,  1,  2, 11,  1,  2,  3,  8,
        9,  2,  3,  4, 10, 11,  3,  4,  5,  9,  4,  5,  6, 10,  5,  6,  7,
        8,  9], dtype=int32), array([ 0,  5,  9, 13, 18, 23, 27, 31, 36, 36, 36, 36, 36], dtype=int32))


## Vertex-to-Vertex Relations

In [7]:
print(igl.adjacency_list(cube_f))

[[1, 2, 4, 6, 7], [0, 2, 3, 7], [0, 1, 3, 4], [1, 2, 4, 5, 7], [0, 2, 3, 5, 6], [3, 4, 6, 7], [0, 4, 5, 7], [0, 1, 3, 5, 6]]


## Shading

Meshplot requires per vertex normals, so we need to "explode" the mesh

In [8]:
explode_f=cube_f
explode_v=cube_v
# print(explode_f)
# print(explode_v)

In [9]:
explode_v=np.array([explode_v[v] for v in (f for f in explode_f)])
explode_v.resize([explode_f.shape[0]*explode_f.shape[1],3])
print(explode_v)
explode_f=np.array([[3*i,3*i+1,3*i+2] for i in range(explode_f.shape[0])])
print(explode_f)

[[-0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5]
 [-0.5  0.5  0.5]
 [-0.5  0.5  0.5]
 [ 0.5 -0.5  0.5]
 [ 0.5  0.5  0.5]
 [-0.5  0.5  0.5]
 [ 0.5  0.5  0.5]
 [-0.5  0.5 -0.5]
 [-0.5  0.5 -0.5]
 [ 0.5  0.5  0.5]
 [ 0.5  0.5 -0.5]
 [-0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5]
 [-0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5]
 [ 0.5  0.5 -0.5]
 [ 0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5]
 [-0.5 -0.5  0.5]
 [ 0.5 -0.5 -0.5]
 [ 0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5]
 [ 0.5 -0.5 -0.5]
 [ 0.5  0.5  0.5]
 [ 0.5  0.5  0.5]
 [ 0.5 -0.5 -0.5]
 [ 0.5  0.5 -0.5]
 [-0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5]
 [-0.5  0.5 -0.5]
 [-0.5  0.5 -0.5]
 [-0.5 -0.5  0.5]
 [-0.5  0.5  0.5]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]]


### Flat Shading

In [10]:
N=igl.per_face_normals(explode_v, explode_f, np.array([1.0,1.0,1.0]))
meshplot.plot(explode_v, explode_f,n=N,shading={"wireframe": True,"flat": False})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

### Per-vertex Shading

In [11]:
N=igl.per_vertex_normals(explode_v, explode_f)
meshplot.plot(explode_v, explode_f,n=N,shading={"wireframe": True,"flat": False})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

### Per-corner Shading

In [12]:
N=igl.per_corner_normals(explode_v, explode_f,1)
meshplot.plot(explode_v, explode_f,n=N,shading={"wireframe": True,"flat": False})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

## Connected Components

## A simple subdivision scheme